name: AdminWatch
version: 1.2
author: Sinnoh
description: Change the time on the server with your watch!
website: http://german-miner.de

main: me.sinnoh.AdminWatch.AdminWatch

commands:
  adminwatch:
    permissions: adminwatch.admin
    usage: /adminwatch [reload]